export const DISPLAY_ALERT = "DISPLAY_ALERT";
export const CLEAR_ALERT = "CLEAR_ALERT";

export const SETUP_USER_BEGIN = "SETUP_USER_BEGIN";
export const SETUP_USER_SUCCESS = "SETUP_USER_SUCCESS";
export const SETUP_USER_ERROR = "SETUP_USER_ERROR";

export const LOGOUT_USER = "LOGOUT_USER";

export const GET_PROJECT_BEGIN = "GET_PROJECT_BEGIN";
export const GET_PROJECT_SUCCESS = "GET_PROJECT_SUCCESS";
export const GET_PROJECT_ERROR = "GET_PROJECT_ERROR";

export const GET_SINGLE_PROJECT_BEGIN = "GET_SINGLE_PROJECT_BEGIN";
export const GET_SINGLE_PROJECT_SUCCESS = "GET_SINGLE_PROJECT_SUCCESS";
export const GET_SINGLE_PROJECT_ERROR = "GET_SINGLE_PROJECT_ERROR";

export const CREATE_PROJECT_BEGIN = "CREATE_PROJECT_BEGIN";
export const CREATE_PROJECT_SUCCESS = "CREATE_PROJECT_SUCCESS";
export const CREATE_PROJECT_ERROR = "CREATE_PROJECT_ERROR";

export const HANDLE_CHANGE = "HANDLE_CHANGE";

export const CLEAR_VALUES = "CLEAR_VALUES";

export const GET_PROJECT_TICKET_BEGIN = "GET_PROJECT_TICKET_BEGIN";
export const GET_PROJECT_TICKET_SUCCESS = "GET_PROJECT_TICKET_SUCCESS";
export const GET_PROJECT_TICKET_ERROR = "GET_PROJECT_TICKET_ERROR";

export const GET_MY_TICKET_BEGIN = "GET_MY_TICKET_BEGIN";
export const GET_MY_TICKET_SUCCESS = "GET_MY_TICKET_SUCCESS";
export const GET_MY_TICKET_ERROR = "GET_MY_TICKET_ERROR";

export const GET_USER_PROJECT_BEGIN = "GET_USER_PROJECT_BEGIN";
export const GET_USER_PROJECT_SUCCESS = "GET_USER_PROJECT_SUCCESS";
export const GET_USER_PROJECT_ERROR = "GET_USER_PROJECT_ERROR";

export const EDIT_USER_INFO_BEGIN = "EDIT_USER_INFO_BEGIN";
export const EDIT_USER_INFO_SUCCESS = "EDIT_USER_INFO_SUCCESS";
export const EDIT_USER_INFO_ERROR = "EDIT_USER_INFO_ERROR";

export const CREATE_TICKET_BEGIN = "CREATE_TICKET_BEGIN";
export const CREATE_TICKET_SUCCESS = "CREATE_TICKET_SUCCESS";
export const CREATE_TICKET_ERROR = "CREATE_TICKET_ERROR";

export const DELETE_PROJECT_BEGIN = "DELETE_PROJECT_BEGIN";
export const DELETE_PROJECT_ERROR = "DELETE_PROJECT_ERROR";

export const EDIT_FILTERS = "EDIT_FILTERS";
export const FILTERED_TICKETS = "FILTERED_TICKETS";

export const CLEAR_FILTERS = "CLEAR_FILTERS";

export const GET_ALL_TICKETS_BEGIN = "GET_ALL_TICKETS_BEGIN";
export const GET_ALL_TICKETS_SUCCESS = "GET_ALL_TICKETS_SUCCESS";
export const GET_ALL_TICKETS_ERROR = "GET_ALL_TICKETS_ERROR";

export const GET_USER_TICKET_BEGIN = "GET_USER_TICKET_BEGIN";
export const GET_USER_TICKET_SUCCESS = "GET_USER_TICKET_SUCCESS";

export const CLEAR_TICKET_VALUES = "CLEAR_TICKET_VALUES";

export const GET_SINGLE_TICKET_BEGIN = "GET_SINGLE_TICKET_BEGIN";
export const GET_SINGLE_TICKET_SUCCESS = "GET_SINGLE_TICKET_SUCCESS";

export const GET_COMMENT_TICKET_BEGIN = "GET_COMMENT_TICKET_BEGIN";
export const GET_COMMENT_TICKET_SUCCESS = "GET_COMMENT_TICKET_SUCCESS";

export const ADD_COMMENT_BEGIN = "ADD_COMMENT_BEGIN";
export const ADD_COMMENT_SUCCESS = "ADD_COMMENT_SUCCESS";

export const GET_PROJECT_DEV_BEGIN = "GET_PROJECT_DEV_BEGIN";
export const GET_PROJECT_DEV_SUCCESS = "GET_PROJECT_DEV_SUCCESS";

export const ADD_DEV_TICKET_BEGIN = "ADD_DEV_TICKET_BEGIN";
export const ADD_DEV_TICKET_SUCCESS = "ADD_DEV_TICKET_SUCCESS";

export const DELETE_TICKET_BEGIN = "DELETE_TICKET_BEGIN";
export const DELETE_TICKET_SUCCESS = "DELET_TICKET_SUCCESS";
export const DELETE_TICKET_ERROR = "DELETE_TICKET_ERROR";

export const ADD_DEV_PROJECT_BEGIN = "ADD_DEV_PROJECT_BEGIN";
export const ADD_DEV_PROJECT_SUCCESS = "ADD_DEV_PROJECT_SUCCESS";

export const GET_ALL_USERS_BEGIN = "GET_ALL_USERS_BEGIN";
export const GET_ALL_USERS_SUCCESS = "GET_ALL_USERS_SUCCESS";

export const EDIT_USER_FILTERS = "EDIT_USER_FILTERS";
export const FILTERED_USER = "FILTERED_USER";

export const GET_DEVS_ON_SINGLE_PROJECT_SUCCESS =
  "GET_DEVS_ON_SINGLE_PROJECT_SUCCESS";
export const GET_DEVS_ON_SINGLE_PROJECT_BEGIN =
  "GET_DEVS_ON_SINGLE_PROJECT_BEGIN";

export const GET_SINGLE_USER_INFO_BEGIN = "GET_SINGLE_USER_INFO_BEGIN";
export const GET_SINGLE_USER_INFO_SUCCESS = "GET_SINGLE_USER_INFO_SUCCESS";

export const EDIT_PROJECT_SUCCESS = "EDIT_PROJECT_SUCCESS";
export const EDIT_PROJECT_BEGIN = "EDIT_PROJECT_BEGIN";
export const EDIT_PROJECT_ERROR = "EDIT_PROJECT_ERROR";

export const EDIT_TICKET_BEGIN = "EDIT_TICKET_BEGIN";
export const EDIT_TICKET_SUCCESS = "EDIT_TICKET_SUCCESS";
export const EDIT_TICKET_ERROR = "EDIT_TICKET_ERROR";

export const EDIT_USER_BEGIN = "EDIT_USER_BEGIN";
export const EDIT_USER_SUCCESS = "EDIT_USER_SUCCESS";
export const EDIT_USER_ERROR = "EDIT_USER_ERROR";

export const TEST_USER_BEGIN = "TEST_USER_BEGIN";
export const TEST_USER_SUCCESS = "TEST_USER_SUCCESS";
export const TEST_USER_ERROR = "TEST_USER_ERROR";

export const CLOSE_SIDEBAR = "CLOSE_SIDEBAR";
export const OPEN_SIDEBAR = "OPEN_SIDEBAR";
